name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-and-publish-live-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          pip install .[all]
          cd docs
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.