name: testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          lfs: 'true'

      - name: Install and Test
        run: |
          pip install .[all]
          export PYTHONPATH=$PYTHONPATH:${GITHUB_WORKSPACE}/src
          pytest Tests/test_subcortical_segmentation.py
          pytest Tests/test_alignment.py
          pytest Tests/test_readio.py

